version: "3.7"
services:
  app:
    container_name: cms-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
